# Generated by Django 4.2 on 2023-06-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmodel",
            name="good",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="chatmodel",
            name="read",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="chatmodel",
            name="readtext",
            field=models.TextField(blank=True, default="a", null=True),
        ),
    ]
